export const vietnamBanks = [
  {
    id: 43,
    shortName: 'Vietcombank',
    name: 'Ngân hàng Ngoại thương Việt Nam',
    code: 'VCB',
    bin: '970436',
    logo: 'https://cdn.vietqr.io/img/VCB.png',
  },
  {
    id: 17,
    shortName: 'VietinBank',
    name: 'Ngân hàng Công thương Việt Nam',
    code: 'ICB',
    bin: '970415',
    logo: 'https://cdn.vietqr.io/img/ICB.png',
  },
  {
    id: 38,
    shortName: 'Techcombank',
    name: 'Ngân hàng Kỹ thương Việt Nam',
    code: 'TCB',
    bin: '970407',
    logo: 'https://cdn.vietqr.io/img/TCB.png',
  },
  {
    id: 21,
    shortName: 'MBBank',
    name: 'Ngân hàng Quân đội',
    code: 'MB',
    bin: '970422',
    logo: 'https://cdn.vietqr.io/img/MB.png',
  },
  {
    id: 4,
    shortName: 'BIDV',
    name: 'Ngân hàng Đầu tư và Phát triển VN',
    code: 'BIDV',
    bin: '970418',
    logo: 'https://cdn.vietqr.io/img/BIDV.png',
  },
  {
    id: 42,
    shortName: 'Agribank',
    name: 'Ngân hàng NN và PTNT Việt Nam',
    code: 'VBA',
    bin: '970405',
    logo: 'https://cdn.vietqr.io/img/VBA.png',
  },
  {
    id: 2,
    shortName: 'ACB',
    name: 'Ngân hàng Á Châu',
    code: 'ACB',
    bin: '970416',
    logo: 'https://cdn.vietqr.io/img/ACB.png',
  },
  {
    id: 47,
    shortName: 'VPBank',
    name: 'Ngân hàng Việt Nam Thịnh Vượng',
    code: 'VPB',
    bin: '970432',
    logo: 'https://cdn.vietqr.io/img/VPB.png',
  },
  {
    id: 39,
    shortName: 'TPBank',
    name: 'Ngân hàng Tiên Phong',
    code: 'TPB',
    bin: '970423',
    logo: 'https://cdn.vietqr.io/img/TPB.png',
  },
  {
    id: 26,
    shortName: 'OCB',
    name: 'Ngân hàng Phương Đông',
    code: 'OCB',
    bin: '970448',
    logo: 'https://cdn.vietqr.io/img/OCB.png',
  },
  {
    id: 36,
    shortName: 'Sacombank',
    name: 'Ngân hàng Sài Gòn Thương Tín',
    code: 'STB',
    bin: '970403',
    logo: 'https://cdn.vietqr.io/img/STB.png',
  },
];

export const RECOMMENDED_BANK_CODES = [
  'OCB',
  'TPB',
  'TCB',
  'VPB',
  'VCB',
  'ICB',
];
