export interface LocationOption {
  value: string;
  label: string;
}

export const VIETNAM_CITIES: LocationOption[] = [
  { value: 'Hà Nội', label: 'Hà Nội' },
  { value: 'Hồ Chí Minh', label: 'Hồ Chí Minh' },
  { value: 'Đà Nẵng', label: 'Đà Nẵng' },
  { value: 'Hải Phòng', label: 'Hải Phòng' },
  { value: 'Cần Thơ', label: 'Cần Thơ' },
  { value: 'An Giang', label: 'An Giang' },
  { value: 'Bà Rịa - Vũng Tàu', label: 'Bà Rịa - Vũng Tàu' },
  { value: 'Bắc Giang', label: 'Bắc Giang' },
  { value: 'Bắc Kạn', label: 'Bắc Kạn' },
  { value: 'Bạc Liêu', label: 'Bạc Liêu' },
  { value: 'Bắc Ninh', label: 'Bắc Ninh' },
  { value: 'Bến Tre', label: 'Bến Tre' },
  { value: 'Bình Định', label: 'Bình Định' },
  { value: 'Bình Dương', label: 'Bình Dương' },
  { value: 'Bình Phước', label: 'Bình Phước' },
  { value: 'Bình Thuận', label: 'Bình Thuận' },
  { value: 'Cà Mau', label: 'Cà Mau' },
  { value: 'Cao Bằng', label: 'Cao Bằng' },
  { value: 'Đắk Lắk', label: 'Đắk Lắk' },
  { value: 'Đắk Nông', label: 'Đắk Nông' },
  { value: 'Điện Biên', label: 'Điện Biên' },
  { value: 'Đồng Nai', label: 'Đồng Nai' },
  { value: 'Đồng Tháp', label: 'Đồng Tháp' },
  { value: 'Gia Lai', label: 'Gia Lai' },
  { value: 'Hà Giang', label: 'Hà Giang' },
  { value: 'Hà Nam', label: 'Hà Nam' },
  { value: 'Hà Tĩnh', label: 'Hà Tĩnh' },
  { value: 'Hải Dương', label: 'Hải Dương' },
  { value: 'Hậu Giang', label: 'Hậu Giang' },
  { value: 'Hòa Bình', label: 'Hòa Bình' },
  { value: 'Hưng Yên', label: 'Hưng Yên' },
  { value: 'Khánh Hòa', label: 'Khánh Hòa' },
  { value: 'Kiên Giang', label: 'Kiên Giang' },
  { value: 'Kon Tum', label: 'Kon Tum' },
  { value: 'Lai Châu', label: 'Lai Châu' },
  { value: 'Lâm Đồng', label: 'Lâm Đồng' },
  { value: 'Lạng Sơn', label: 'Lạng Sơn' },
  { value: 'Lào Cai', label: 'Lào Cai' },
  { value: 'Long An', label: 'Long An' },
  { value: 'Nam Định', label: 'Nam Định' },
  { value: 'Nghệ An', label: 'Nghệ An' },
  { value: 'Ninh Bình', label: 'Ninh Bình' },
  { value: 'Ninh Thuận', label: 'Ninh Thuận' },
  { value: 'Phú Thọ', label: 'Phú Thọ' },
  { value: 'Phú Yên', label: 'Phú Yên' },
  { value: 'Quảng Bình', label: 'Quảng Bình' },
  { value: 'Quảng Nam', label: 'Quảng Nam' },
  { value: 'Quảng Ngãi', label: 'Quảng Ngãi' },
  { value: 'Quảng Ninh', label: 'Quảng Ninh' },
  { value: 'Quảng Trị', label: 'Quảng Trị' },
  { value: 'Sóc Trăng', label: 'Sóc Trăng' },
  { value: 'Sơn La', label: 'Sơn La' },
  { value: 'Tây Ninh', label: 'Tây Ninh' },
  { value: 'Thái Bình', label: 'Thái Bình' },
  { value: 'Thái Nguyên', label: 'Thái Nguyên' },
  { value: 'Thanh Hóa', label: 'Thanh Hóa' },
  { value: 'Thừa Thiên Huế', label: 'Thừa Thiên Huế' },
  { value: 'Tiền Giang', label: 'Tiền Giang' },
  { value: 'Trà Vinh', label: 'Trà Vinh' },
  { value: 'Tuyên Quang', label: 'Tuyên Quang' },
  { value: 'Vĩnh Long', label: 'Vĩnh Long' },
  { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
  { value: 'Yên Bái', label: 'Yên Bái' },
];

export const VIETNAM_DISTRICTS: Record<string, LocationOption[]> = {
  'Hà Nội': [
    { value: 'Ba Đình', label: 'Ba Đình' },
    { value: 'Bắc Từ Liêm', label: 'Bắc Từ Liêm' },
    { value: 'Ba Vì', label: 'Ba Vì' },
    { value: 'Cầu Giấy', label: 'Cầu Giấy' },
    { value: 'Chương Mỹ', label: 'Chương Mỹ' },
    { value: 'Đan Phượng', label: 'Đan Phượng' },
    { value: 'Đông Anh', label: 'Đông Anh' },
    { value: 'Đống Đa', label: 'Đống Đa' },
    { value: 'Gia Lâm', label: 'Gia Lâm' },
    { value: 'Hà Đông', label: 'Hà Đông' },
    { value: 'Hai Bà Trưng', label: 'Hai Bà Trưng' },
    { value: 'Hoài Đức', label: 'Hoài Đức' },
    { value: 'Hoàn Kiếm', label: 'Hoàn Kiếm' },
    { value: 'Hoàng Mai', label: 'Hoàng Mai' },
    { value: 'Long Biên', label: 'Long Biên' },
    { value: 'Mê Linh', label: 'Mê Linh' },
    { value: 'Mỹ Đức', label: 'Mỹ Đức' },
    { value: 'Nam Từ Liêm', label: 'Nam Từ Liêm' },
    { value: 'Phú Xuyên', label: 'Phú Xuyên' },
    { value: 'Phúc Thọ', label: 'Phúc Thọ' },
    { value: 'Quốc Oai', label: 'Quốc Oai' },
    { value: 'Sóc Sơn', label: 'Sóc Sơn' },
    { value: 'Sơn Tây', label: 'Sơn Tây' },
    { value: 'Tây Hồ', label: 'Tây Hồ' },
    { value: 'Thạch Thất', label: 'Thạch Thất' },
    { value: 'Thanh Oai', label: 'Thanh Oai' },
    { value: 'Thanh Trì', label: 'Thanh Trì' },
    { value: 'Thanh Xuân', label: 'Thanh Xuân' },
    { value: 'Thường Tín', label: 'Thường Tín' },
    { value: 'Ứng Hòa', label: 'Ứng Hòa' },
  ],
  'Hồ Chí Minh': [
    { value: 'Bình Chánh', label: 'Bình Chánh' },
    { value: 'Bình Tân', label: 'Bình Tân' },
    { value: 'Bình Thạnh', label: 'Bình Thạnh' },
    { value: 'Cần Giờ', label: 'Cần Giờ' },
    { value: 'Củ Chi', label: 'Củ Chi' },
    { value: 'Gò Vấp', label: 'Gò Vấp' },
    { value: 'Hóc Môn', label: 'Hóc Môn' },
    { value: 'Nhà Bè', label: 'Nhà Bè' },
    { value: 'Phú Nhuận', label: 'Phú Nhuận' },
    { value: 'Quận 1', label: 'Quận 1' },
    { value: 'Quận 2', label: 'Quận 2' },
    { value: 'Quận 3', label: 'Quận 3' },
    { value: 'Quận 4', label: 'Quận 4' },
    { value: 'Quận 5', label: 'Quận 5' },
    { value: 'Quận 6', label: 'Quận 6' },
    { value: 'Quận 7', label: 'Quận 7' },
    { value: 'Quận 8', label: 'Quận 8' },
    { value: 'Quận 9', label: 'Quận 9' },
    { value: 'Quận 10', label: 'Quận 10' },
    { value: 'Quận 11', label: 'Quận 11' },
    { value: 'Quận 12', label: 'Quận 12' },
    { value: 'Tân Bình', label: 'Tân Bình' },
    { value: 'Tân Phú', label: 'Tân Phú' },
    { value: 'Thủ Đức', label: 'Thủ Đức' },
  ],
  'Đà Nẵng': [
    { value: 'Cẩm Lệ', label: 'Cẩm Lệ' },
    { value: 'Hải Châu', label: 'Hải Châu' },
    { value: 'Hòa Vang', label: 'Hòa Vang' },
    { value: 'Liên Chiểu', label: 'Liên Chiểu' },
    { value: 'Ngũ Hành Sơn', label: 'Ngũ Hành Sơn' },
    { value: 'Sơn Trà', label: 'Sơn Trà' },
    { value: 'Thanh Khê', label: 'Thanh Khê' },
  ],
  'Hải Phòng': [
    { value: 'An Dương', label: 'An Dương' },
    { value: 'An Lão', label: 'An Lão' },
    { value: 'Bạch Long Vĩ', label: 'Bạch Long Vĩ' },
    { value: 'Cát Hải', label: 'Cát Hải' },
    { value: 'Đồ Sơn', label: 'Đồ Sơn' },
    { value: 'Dương Kinh', label: 'Dương Kinh' },
    { value: 'Hải An', label: 'Hải An' },
    { value: 'Hồng Bàng', label: 'Hồng Bàng' },
    { value: 'Kiến An', label: 'Kiến An' },
    { value: 'Kiến Thụy', label: 'Kiến Thụy' },
    { value: 'Lê Chân', label: 'Lê Chân' },
    { value: 'Ngô Quyền', label: 'Ngô Quyền' },
    { value: 'Thủy Nguyên', label: 'Thủy Nguyên' },
    { value: 'Tiên Lãng', label: 'Tiên Lãng' },
    { value: 'Vĩnh Bảo', label: 'Vĩnh Bảo' },
  ],
  'Cần Thơ': [
    { value: 'Bình Thủy', label: 'Bình Thủy' },
    { value: 'Cái Răng', label: 'Cái Răng' },
    { value: 'Cờ Đỏ', label: 'Cờ Đỏ' },
    { value: 'Ninh Kiều', label: 'Ninh Kiều' },
    { value: 'Ô Môn', label: 'Ô Môn' },
    { value: 'Phong Điền', label: 'Phong Điền' },
    { value: 'Thốt Nốt', label: 'Thốt Nốt' },
    { value: 'Thới Lai', label: 'Thới Lai' },
    { value: 'Vĩnh Thạnh', label: 'Vĩnh Thạnh' },
  ],
  'Bình Dương': [
    { value: 'Bàu Bàng', label: 'Bàu Bàng' },
    { value: 'Bắc Tân Uyên', label: 'Bắc Tân Uyên' },
    { value: 'Bến Cát', label: 'Bến Cát' },
    { value: 'Dầu Tiếng', label: 'Dầu Tiếng' },
    { value: 'Dĩ An', label: 'Dĩ An' },
    { value: 'Phú Giáo', label: 'Phú Giáo' },
    { value: 'Tân Uyên', label: 'Tân Uyên' },
    { value: 'Thủ Dầu Một', label: 'Thủ Dầu Một' },
    { value: 'Thuận An', label: 'Thuận An' },
  ],
  'Đồng Nai': [
    { value: 'Biên Hòa', label: 'Biên Hòa' },
    { value: 'Cẩm Mỹ', label: 'Cẩm Mỹ' },
    { value: 'Định Quán', label: 'Định Quán' },
    { value: 'Long Khánh', label: 'Long Khánh' },
    { value: 'Long Thành', label: 'Long Thành' },
    { value: 'Nhơn Trạch', label: 'Nhơn Trạch' },
    { value: 'Tân Phú', label: 'Tân Phú' },
    { value: 'Thống Nhất', label: 'Thống Nhất' },
    { value: 'Trảng Bom', label: 'Trảng Bom' },
    { value: 'Vĩnh Cửu', label: 'Vĩnh Cửu' },
    { value: 'Xuân Lộc', label: 'Xuân Lộc' },
  ],
  'Khánh Hòa': [
    { value: 'Cam Lâm', label: 'Cam Lâm' },
    { value: 'Cam Ranh', label: 'Cam Ranh' },
    { value: 'Diên Khánh', label: 'Diên Khánh' },
    { value: 'Khánh Sơn', label: 'Khánh Sơn' },
    { value: 'Khánh Vĩnh', label: 'Khánh Vĩnh' },
    { value: 'Nha Trang', label: 'Nha Trang' },
    { value: 'Ninh Hòa', label: 'Ninh Hòa' },
    { value: 'Trường Sa', label: 'Trường Sa' },
    { value: 'Vạn Ninh', label: 'Vạn Ninh' },
  ],
  'Lâm Đồng': [
    { value: 'Bảo Lâm', label: 'Bảo Lâm' },
    { value: 'Bảo Lộc', label: 'Bảo Lộc' },
    { value: 'Cát Tiên', label: 'Cát Tiên' },
    { value: 'Đà Lạt', label: 'Đà Lạt' },
    { value: 'Đạ Huoai', label: 'Đạ Huoai' },
    { value: 'Đạ Tẻh', label: 'Đạ Tẻh' },
    { value: 'Đam Rông', label: 'Đam Rông' },
    { value: 'Di Linh', label: 'Di Linh' },
    { value: 'Đơn Dương', label: 'Đơn Dương' },
    { value: 'Đức Trọng', label: 'Đức Trọng' },
    { value: 'Lạc Dương', label: 'Lạc Dương' },
    { value: 'Lâm Hà', label: 'Lâm Hà' },
  ],
  'Nghệ An': [
    { value: 'Anh Sơn', label: 'Anh Sơn' },
    { value: 'Con Cuông', label: 'Con Cuông' },
    { value: 'Cửa Lò', label: 'Cửa Lò' },
    { value: 'Diễn Châu', label: 'Diễn Châu' },
    { value: 'Đô Lương', label: 'Đô Lương' },
    { value: 'Hoàng Mai', label: 'Hoàng Mai' },
    { value: 'Hưng Nguyên', label: 'Hưng Nguyên' },
    { value: 'Kỳ Sơn', label: 'Kỳ Sơn' },
    { value: 'Nam Đàn', label: 'Nam Đàn' },
    { value: 'Nghi Lộc', label: 'Nghi Lộc' },
    { value: 'Nghĩa Đàn', label: 'Nghĩa Đàn' },
    { value: 'Quế Phong', label: 'Quế Phong' },
    { value: 'Quỳ Châu', label: 'Quỳ Châu' },
    { value: 'Quỳ Hợp', label: 'Quỳ Hợp' },
    { value: 'Quỳnh Lưu', label: 'Quỳnh Lưu' },
    { value: 'Tân Kỳ', label: 'Tân Kỳ' },
    { value: 'Thái Hòa', label: 'Thái Hòa' },
    { value: 'Thanh Chương', label: 'Thanh Chương' },
    { value: 'Tương Dương', label: 'Tương Dương' },
    { value: 'Vinh', label: 'Vinh' },
    { value: 'Yên Thành', label: 'Yên Thành' },
  ],
  'Thanh Hóa': [
    { value: 'Bá Thước', label: 'Bá Thước' },
    { value: 'Bỉm Sơn', label: 'Bỉm Sơn' },
    { value: 'Cẩm Thủy', label: 'Cẩm Thủy' },
    { value: 'Đông Sơn', label: 'Đông Sơn' },
    { value: 'Hà Trung', label: 'Hà Trung' },
    { value: 'Hậu Lộc', label: 'Hậu Lộc' },
    { value: 'Hoằng Hóa', label: 'Hoằng Hóa' },
    { value: 'Lang Chánh', label: 'Lang Chánh' },
    { value: 'Mường Lát', label: 'Mường Lát' },
    { value: 'Nga Sơn', label: 'Nga Sơn' },
    { value: 'Ngọc Lặc', label: 'Ngọc Lặc' },
    { value: 'Như Thanh', label: 'Như Thanh' },
    { value: 'Như Xuân', label: 'Như Xuân' },
    { value: 'Nông Cống', label: 'Nông Cống' },
    { value: 'Quan Hóa', label: 'Quan Hóa' },
    { value: 'Quan Sơn', label: 'Quan Sơn' },
    { value: 'Quảng Xương', label: 'Quảng Xương' },
    { value: 'Sầm Sơn', label: 'Sầm Sơn' },
    { value: 'Thạch Thành', label: 'Thạch Thành' },
    { value: 'Thiệu Hóa', label: 'Thiệu Hóa' },
    { value: 'Thọ Xuân', label: 'Thọ Xuân' },
    { value: 'Thường Xuân', label: 'Thường Xuân' },
    { value: 'Tĩnh Gia', label: 'Tĩnh Gia' },
    { value: 'Triệu Sơn', label: 'Triệu Sơn' },
    { value: 'Vĩnh Lộc', label: 'Vĩnh Lộc' },
    { value: 'Yên Định', label: 'Yên Định' },
    { value: 'Thanh Hóa', label: 'TP. Thanh Hóa' },
  ],
  'Thừa Thiên Huế': [
    { value: 'A Lưới', label: 'A Lưới' },
    { value: 'Huế', label: 'Huế' },
    { value: 'Hương Thủy', label: 'Hương Thủy' },
    { value: 'Hương Trà', label: 'Hương Trà' },
    { value: 'Nam Đông', label: 'Nam Đông' },
    { value: 'Phong Điền', label: 'Phong Điền' },
    { value: 'Phú Lộc', label: 'Phú Lộc' },
    { value: 'Phú Vang', label: 'Phú Vang' },
    { value: 'Quảng Điền', label: 'Quảng Điền' },
  ],
  'Quảng Nam': [
    { value: 'Bắc Trà My', label: 'Bắc Trà My' },
    { value: 'Duy Xuyên', label: 'Duy Xuyên' },
    { value: 'Đại Lộc', label: 'Đại Lộc' },
    { value: 'Điện Bàn', label: 'Điện Bàn' },
    { value: 'Đông Giang', label: 'Đông Giang' },
    { value: 'Hiệp Đức', label: 'Hiệp Đức' },
    { value: 'Hội An', label: 'Hội An' },
    { value: 'Nam Giang', label: 'Nam Giang' },
    { value: 'Nam Trà My', label: 'Nam Trà My' },
    { value: 'Núi Thành', label: 'Núi Thành' },
    { value: 'Phú Ninh', label: 'Phú Ninh' },
    { value: 'Phước Sơn', label: 'Phước Sơn' },
    { value: 'Quế Sơn', label: 'Quế Sơn' },
    { value: 'Tây Giang', label: 'Tây Giang' },
    { value: 'Tam Kỳ', label: 'Tam Kỳ' },
    { value: 'Thăng Bình', label: 'Thăng Bình' },
    { value: 'Tiên Phước', label: 'Tiên Phước' },
  ],
};

/**
 * Returns districts for the given city, or empty array if not mapped.
 */
export function getDistrictsByCity(city: string): LocationOption[] {
  return VIETNAM_DISTRICTS[city] ?? [];
}
