'use client';

import { Box, Flex, Heading, HStack, Text, VStack } from '@chakra-ui/react';
import { Banknote } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { Button } from '@/components/ui/chakra-compat';
import { VenuePriceBook } from '@/lib/api/types';
import {
  PricingTableRow,
  formatTablePrice,
  groupPricingRowsByDay,
  isAutoGeneratedPricingNote,
} from '@/utils/venue-pricing';

interface VenuePricingSectionProps {
  rows: PricingTableRow[];
  activePriceBook?: VenuePriceBook;
  canEditPricing?: boolean;
  onEditPricing?: () => void;
}

const VenuePricingSection = ({
  rows,
  activePriceBook,
  canEditPricing,
  onEditPricing,
}: VenuePricingSectionProps) => {
  const t = useTranslations('venue');
  const hasRows = rows.length > 0;
  const notes =
    activePriceBook?.notes && !isAutoGeneratedPricingNote(activePriceBook.notes)
      ? activePriceBook.notes
      : undefined;

  return (
    <Box
      p={{ base: 4, md: 6 }}
      bg="white"
      _dark={{ bg: 'gray.800', borderColor: 'gray.700' }}
      borderRadius="2xl"
      borderWidth="1px"
      borderColor="gray.100"
      shadow="sm"
    >
      <Flex
        align={{ base: 'flex-start', sm: 'center' }}
        justify="space-between"
        gap={3}
        mb={hasRows ? 4 : 2}
        direction={{ base: 'column', sm: 'row' }}
      >
        <Flex align="center" gap={3}>
          <Box
            p={2.5}
            borderRadius="xl"
            bg="orange.50"
            _dark={{ bg: 'orange.900/30' }}
            flexShrink={0}
          >
            <Banknote size={20} color="#DD6B20" />
          </Box>
          <Heading size="md" fontWeight="bold">
            {t('detail.pricing')}
          </Heading>
        </Flex>
        {canEditPricing && !hasRows && onEditPricing && (
          <HStack gap={2}>
            <Button
              variant="outline"
              size="sm"
              colorPalette="green"
              onClick={onEditPricing}
            >
              <Banknote size={14} />
              {t('detail.updatePricing')}
            </Button>
          </HStack>
        )}
      </Flex>

      {!hasRows && (
        <Text
          fontSize="sm"
          color="gray.400"
          _dark={{ color: 'gray.500' }}
          fontStyle="italic"
        >
          {t('detail.noPricing')}
        </Text>
      )}

      {hasRows && (
        <>
          {/* Mobile: grouped list — the 4-column table needs 640px and would
              force horizontal scrolling on a phone. */}
          <VStack
            display={{ base: 'flex', md: 'none' }}
            gap={3}
            align="stretch"
          >
            {groupPricingRowsByDay(rows).map((group) => (
              <Box
                key={group.dayLabel}
                borderWidth="1px"
                borderColor="green.200"
                _dark={{ borderColor: 'green.700' }}
                borderRadius="xl"
                overflow="hidden"
              >
                <Box
                  px={3}
                  py={2}
                  bg="green.50"
                  _dark={{ bg: 'green.950' }}
                  fontSize="sm"
                  fontWeight="bold"
                  color="green.800"
                >
                  {group.dayLabel}
                </Box>
                <VStack gap={0} align="stretch">
                  {group.rows.map((row) => {
                    // Most venues charge the same rate to both customer types;
                    // repeating it twice is pure noise.
                    const isSameRate =
                      !!row.fixed && !!row.walkIn && row.fixed === row.walkIn;

                    return (
                      <Flex
                        key={`${group.dayLabel}-${row.timeLabel}`}
                        px={3}
                        py={2.5}
                        gap={3}
                        align="center"
                        justify="space-between"
                        borderTopWidth="1px"
                        borderTopColor="green.100"
                        _dark={{ borderTopColor: 'green.800' }}
                      >
                        <Text
                          fontSize="sm"
                          fontWeight="semibold"
                          flexShrink={0}
                        >
                          {row.timeLabel}
                        </Text>
                        {isSameRate ? (
                          <Text
                            fontSize="sm"
                            fontWeight="semibold"
                            whiteSpace="nowrap"
                          >
                            {formatTablePrice(row.fixed)}
                          </Text>
                        ) : (
                          <VStack gap={0.5} align="flex-end" minW={0}>
                            {row.fixed && (
                              <Text fontSize="sm" whiteSpace="nowrap">
                                <Box as="span" color="gray.500">
                                  {t('detail.fixedLabel')}{' '}
                                </Box>
                                <Box as="span" fontWeight="semibold">
                                  {formatTablePrice(row.fixed)}
                                </Box>
                              </Text>
                            )}
                            {row.walkIn && (
                              <Text fontSize="sm" whiteSpace="nowrap">
                                <Box as="span" color="gray.500">
                                  {t('detail.walkInLabel')}{' '}
                                </Box>
                                <Box as="span" fontWeight="semibold">
                                  {formatTablePrice(row.walkIn)}
                                </Box>
                              </Text>
                            )}
                          </VStack>
                        )}
                      </Flex>
                    );
                  })}
                </VStack>
              </Box>
            ))}
          </VStack>

          {/* Desktop: full comparison table */}
          <Box display={{ base: 'none', md: 'block' }} overflowX="auto">
            <Box
              as="table"
              w="full"
              minW="640px"
              borderWidth="1px"
              borderColor="green.700"
              borderCollapse="collapse"
              color="green.900"
              _dark={{ color: 'green.100', borderColor: 'green.500' }}
            >
              <Box as="thead">
                <Box as="tr">
                  {[
                    t('detail.tableDay'),
                    t('detail.tableTime'),
                    t('detail.tableFixed'),
                    t('detail.tableWalkIn'),
                  ].map((heading) => (
                    <Box
                      key={heading}
                      as="th"
                      py={4}
                      px={4}
                      borderWidth="1px"
                      borderColor="green.700"
                      bg="green.50"
                      fontSize="md"
                      fontWeight="bold"
                      textAlign="center"
                      _dark={{ bg: 'green.950', borderColor: 'green.500' }}
                    >
                      {heading}
                    </Box>
                  ))}
                </Box>
              </Box>
              <Box as="tbody">
                {rows.map((row, index) => {
                  const previousRow = rows[index - 1];
                  const showDay =
                    !previousRow || previousRow.dayLabel !== row.dayLabel;
                  const rowSpan = rows.filter(
                    (item) => item.dayLabel === row.dayLabel
                  ).length;

                  return (
                    <Box as="tr" key={`${row.dayLabel}-${row.timeLabel}`}>
                      {showDay && (
                        <Box
                          as="td"
                          {...{ rowSpan }}
                          py={4}
                          px={4}
                          borderWidth="1px"
                          borderColor="green.700"
                          fontWeight="semibold"
                          textAlign="center"
                          verticalAlign="middle"
                          _dark={{ borderColor: 'green.500' }}
                        >
                          {row.dayLabel}
                        </Box>
                      )}
                      <Box
                        as="td"
                        py={3}
                        px={4}
                        borderWidth="1px"
                        borderColor="green.700"
                        textAlign="center"
                        _dark={{ borderColor: 'green.500' }}
                      >
                        {row.timeLabel}
                      </Box>
                      <Box
                        as="td"
                        py={3}
                        px={4}
                        borderWidth="1px"
                        borderColor="green.700"
                        fontWeight="medium"
                        textAlign="center"
                        _dark={{ borderColor: 'green.500' }}
                      >
                        {formatTablePrice(row.fixed)}
                      </Box>
                      <Box
                        as="td"
                        py={3}
                        px={4}
                        borderWidth="1px"
                        borderColor="green.700"
                        fontWeight="medium"
                        textAlign="center"
                        _dark={{ borderColor: 'green.500' }}
                      >
                        {formatTablePrice(row.walkIn)}
                      </Box>
                    </Box>
                  );
                })}
              </Box>
            </Box>
          </Box>

          {notes && (
            <Text
              fontSize="sm"
              color="gray.500"
              _dark={{ color: 'gray.400' }}
              mt={3}
            >
              {notes}
            </Text>
          )}
        </>
      )}
    </Box>
  );
};

export default VenuePricingSection;
