import {
  VenueCustomerType,
  VenueDayType,
  VenuePriceBook,
  VenuePriceRule,
} from '@/lib/api/types';

export type VenueT = (
  key: string,
  values?: Record<string, string | number>
) => string;

export interface PricingTableRow {
  dayLabel: string;
  daySort: number;
  timeLabel: string;
  startMinute: number;
  fixed?: number;
  walkIn?: number;
}

export const formatTablePrice = (amount?: number) => {
  if (!amount) return '-';
  return new Intl.NumberFormat('vi-VN').format(amount) + ' đ';
};

const minuteToHourLabel = (value: number) => {
  if (value === 1440) return '24h';

  const hours = Math.floor(value / 60);
  const minutes = value % 60;
  return minutes === 0
    ? `${hours}h`
    : `${hours}h${minutes.toString().padStart(2, '0')}`;
};

const formatTimeRange = (startMinute: number, endMinute: number) =>
  `${minuteToHourLabel(startMinute)} - ${minuteToHourLabel(endMinute)}`;

const compactWeekdayLabel = (daysOfWeek: number[] | undefined, t: VenueT) => {
  const days = [...new Set(daysOfWeek || [])].sort((a, b) => a - b);
  if (days.length === 0) return t('detail.day.byWeekday');
  if (days.join(',') === '1,2,3,4,5') return t('detail.day.weekdays');
  if (days.join(',') === '6,7') return t('detail.day.weekend');
  if (days.join(',') === '1,2,3,4,5,6,7') return t('detail.day.everyday');

  return days.map((day) => t(`detail.weekday.d${day}`)).join(', ');
};

const getRuleDayLabel = (rule: VenuePriceRule, t: VenueT) => {
  if (rule.dayType === VenueDayType.EVERYDAY) return t('detail.day.everyday');
  if (rule.dayType === VenueDayType.WEEKEND) return t('detail.day.weekend');
  if (rule.dayType === VenueDayType.WEEKDAY) {
    return compactWeekdayLabel(rule.daysOfWeek, t);
  }
  if (rule.dayType === VenueDayType.HOLIDAY) return t('detail.day.holiday');
  if (rule.dayType === VenueDayType.SPECIFIC_DATE && rule.specificDate) {
    return new Date(rule.specificDate).toLocaleDateString('vi-VN');
  }

  return t('detail.day.other');
};

const getRuleDaySort = (rule: VenuePriceRule) => {
  if (rule.dayType === VenueDayType.EVERYDAY) return 0;
  if (rule.dayType === VenueDayType.WEEKDAY) {
    return Math.min(...(rule.daysOfWeek?.length ? rule.daysOfWeek : [1]));
  }
  if (rule.dayType === VenueDayType.WEEKEND) return 6;
  if (rule.dayType === VenueDayType.HOLIDAY) return 8;
  return 9;
};

/**
 * Legacy price books created by the pricing migration carry system-generated
 * notes (e.g. "Tự động tạo từ giá thuê cố định/vãng lai cũ"). These are
 * internal artifacts, not real venue notes or public pricing.
 */
export const isAutoGeneratedPricingNote = (notes?: string | null) =>
  !!notes && notes.trimStart().startsWith('Tự động tạo từ');

export const getActivePriceBook = (priceBooks: VenuePriceBook[]) =>
  [...priceBooks]
    .filter((book) => book.isActive && !isAutoGeneratedPricingNote(book.notes))
    .sort((a, b) => {
      const priorityDiff = (b.priority || 0) - (a.priority || 0);
      if (priorityDiff !== 0) return priorityDiff;
      return (
        new Date(b.effectiveFrom).getTime() -
        new Date(a.effectiveFrom).getTime()
      );
    })[0];

export const buildPricingRows = (
  priceBook: VenuePriceBook | undefined,
  t: VenueT
) => {
  const rows = new Map<string, PricingTableRow>();

  (priceBook?.rules || []).forEach((rule) => {
    if (
      rule.customerType !== VenueCustomerType.FIXED &&
      rule.customerType !== VenueCustomerType.WALK_IN
    ) {
      return;
    }

    const dayLabel = getRuleDayLabel(rule, t);
    const timeLabel = formatTimeRange(rule.startMinute, rule.endMinute);
    const key = `${dayLabel}-${rule.startMinute}-${rule.endMinute}`;
    const current = rows.get(key) || {
      dayLabel,
      daySort: getRuleDaySort(rule),
      timeLabel,
      startMinute: rule.startMinute,
    };

    if (rule.customerType === VenueCustomerType.FIXED) {
      current.fixed = rule.pricePerHour;
    } else {
      current.walkIn = rule.pricePerHour;
    }

    rows.set(key, current);
  });

  return [...rows.values()].sort((a, b) => {
    const dayDiff = a.daySort - b.daySort;
    if (dayDiff !== 0) return dayDiff;
    return a.startMinute - b.startMinute;
  });
};

export const getMinPricePerHour = (rows: PricingTableRow[]) => {
  const prices = rows
    .flatMap((row) => [row.fixed, row.walkIn])
    .filter((price): price is number => !!price);
  return prices.length ? Math.min(...prices) : undefined;
};

/** Rows grouped by day label, preserving the sorted order of `rows`. */
export const groupPricingRowsByDay = (rows: PricingTableRow[]) => {
  const groups = new Map<string, PricingTableRow[]>();
  rows.forEach((row) => {
    const group = groups.get(row.dayLabel);
    if (group) {
      group.push(row);
      return;
    }
    groups.set(row.dayLabel, [row]);
  });
  return [...groups.entries()].map(([dayLabel, dayRows]) => ({
    dayLabel,
    rows: dayRows,
  }));
};
